ProxyMode=0
Server=192.168.42.2:10051;192.168.42.3:10051
Hostname=EIT-ZBX-Proxy02
LogFile=/var/log/zabbix/zabbix_proxy.log
LogFileSize=100
PidFile=/run/zabbix/zabbix_proxy.pid
SocketDir=/run/zabbix
DBName=/var/lib/zabbix/zabbix_proxy.db
ProxyBufferMode=hybrid
ProxyMemoryBufferSize=128M
ProxyOfflineBuffer=24
CacheSize=128M
StartPollers=5
StartAgentPollers=2
StartSNMPPollers=2
StartHTTPAgentPollers=2
StartHTTPPollers=2
StartPollersUnreachable=2
StartPingers=2
StartPreprocessors=4
Timeout=5
FpingLocation=/usr/bin/fping
